#!/usr/bin/env bash
# This script transfers a file to a remote server using SCP with the key authentication

# Exit on any error
set -e

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to named variables
FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file to the user's home directory using SCP
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP:~/"