#!/usr/bin/env bash
# Transfer file from client to server
args_count=$(( $# - 1))
if [ "$args_count" -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -T -o StrictHostKeyChecking=no  "$1"  "$3@$2:~/" 
fi